name: Deploy image service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH, create .env and deploy image service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www
            sudo mkdir dot-pablomag
            cd dot-pablomag
            sudo git clone https://github.com/pablomag/dot-pablomag-imgserver.git
            sudo mv dot-pablomag-imgserver imgserver
            cd imgserver
            sudo mkdir data
            sudo mkdir data/images
            sudo mkdir data/images/mobile
            sudo mkdir data/images/desktop
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} data
            sudo npm install pm2 -g
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install yarn -y
            sudo touch .env
            sudo bash -c "echo SERVICE_PORT=${{ secrets.SERVICE_PORT }} >> .env"
            sudo bash -c "echo API_URL=${{ secrets.API_URL }} >> .env"
            sudo bash -c "echo API_SECRET='`echo ${{ secrets.API_SECRET }} | base64 --decode`' >> .env"
            sudo bash -c "echo PROVIDER_URI=${{ secrets.PROVIDER_URI }} >> .env"
            sudo bash -c "echo PROVIDER_CLIENT_ID='`echo ${{ secrets.PROVIDER_CLIENT_ID }} | base64 --decode`' >> .env"
            sudo yarn install
            sudo yarn build
            pm2 start pm2.config.js
            pm2 startup systemd -u ${{ secrets.SSH_USER }}
            pm2 save --force
