name: Deploy update

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH, update .env and image service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/dot-pablomag/imgserver
            sudo git pull
            sudo rm .env
            sudo touch .env
            sudo bash -c "echo SERVICE_PORT=${{ secrets.SERVICE_PORT }} >> .env"
            sudo bash -c "echo API_URL=${{ secrets.API_URL }} >> .env"
            sudo bash -c "echo API_SECRET='`echo ${{ secrets.API_SECRET }} | base64 --decode`' >> .env"
            sudo bash -c "echo PROVIDER_URI=${{ secrets.PROVIDER_URI }} >> .env"
            sudo bash -c "echo PROVIDER_CLIENT_ID='`echo ${{ secrets.PROVIDER_CLIENT_ID }} | base64 --decode`' >> .env"
            sudo yarn install
            sudo yarn build
            pm2 restart pm2.config.js
